import type {Locale} from './locales';
export const watchCopy:Record<Locale,{title:string;body:string;note:string}>={
ja:{title:'ウォッチの記録を、\n毎日の睡眠日誌へ。',body:'Apple Watchや対応するスマートウォッチで記録した睡眠データを取り込み、睡眠記録に自動反映。毎朝の手入力の手間を減らせます。',note:'利用できる連携は、OS・機器・データ共有の設定によって異なります。手入力でも記録できます。'},
en:{title:'From your watch\nto your sleep journal.',body:'Import sleep data recorded by Apple Watch or a compatible smartwatch and automatically fill your sleep record, reducing manual entry each morning.',note:'Available integrations depend on your OS, device and data-sharing settings. You can also enter records manually.'},
'zh-CN':{title:'将手表记录\n带入每日睡眠日记。',body:'导入Apple Watch或兼容智能手表记录的睡眠数据，自动填入睡眠记录，减少每天早晨的手动输入。',note:'可用的连接取决于操作系统、设备和数据共享设置。也可手动记录。'},
'zh-TW':{title:'將手錶記錄\n帶入每日睡眠日誌。',body:'匯入Apple Watch或相容智慧手錶記錄的睡眠資料，自動填入睡眠記錄，減少每天早晨的手動輸入。',note:'可用的連動取決於作業系統、裝置和資料共享設定。也可手動記錄。'},
ko:{title:'워치의 기록을\n매일의 수면 일지로.',body:'Apple Watch나 호환 스마트워치에 기록된 수면 데이터를 가져와 수면 기록에 자동으로 반영합니다. 매일 아침 직접 입력하는 수고를 줄이세요.',note:'사용 가능한 연동은 OS, 기기 및 데이터 공유 설정에 따라 다릅니다. 직접 입력할 수도 있습니다.'},
de:{title:'Von Ihrer Uhr\nin Ihr Schlaftagebuch.',body:'Importieren Sie Schlafdaten von der Apple Watch oder einer kompatiblen Smartwatch und füllen Sie Ihren Schlafeintrag automatisch aus – für weniger manuelle Eingaben am Morgen.',note:'Verfügbare Integrationen hängen von Betriebssystem, Gerät und Datenfreigabe ab. Manuelle Einträge sind ebenfalls möglich.'},
fr:{title:'De votre montre\nà votre journal de sommeil.',body:'Importez les données de sommeil de votre Apple Watch ou d’une montre connectée compatible pour remplir automatiquement votre journal et réduire la saisie chaque matin.',note:'Les intégrations disponibles dépendent du système, de l’appareil et des réglages de partage. La saisie manuelle reste possible.'},
es:{title:'De tu reloj\na tu diario de sueño.',body:'Importa los datos de sueño de Apple Watch o un reloj compatible y completa automáticamente tu registro, reduciendo la introducción manual cada mañana.',note:'Las integraciones dependen del sistema operativo, el dispositivo y los ajustes para compartir datos. También puedes registrar el sueño manualmente.'},
it:{title:'Dal tuo orologio\nal diario del sonno.',body:'Importa i dati del sonno da Apple Watch o da uno smartwatch compatibile e compila automaticamente il diario, riducendo gli inserimenti manuali ogni mattina.',note:'Le integrazioni dipendono dal sistema operativo, dal dispositivo e dalle impostazioni di condivisione. Puoi anche inserire i dati manualmente.'},
'pt-BR':{title:'Do seu relógio\npara o diário do sono.',body:'Importe dados de sono do Apple Watch ou de um smartwatch compatível e preencha seu registro automaticamente, reduzindo a digitação a cada manhã.',note:'As integrações dependem do sistema operacional, dispositivo e configurações de compartilhamento. Você também pode registrar manualmente.'},
nl:{title:'Van je horloge\nnaar je slaapdagboek.',body:'Importeer slaapgegevens van Apple Watch of een compatibele smartwatch en vul je slaapregistratie automatisch in, met minder handmatige invoer in de ochtend.',note:'Beschikbare koppelingen hangen af van je besturingssysteem, apparaat en instellingen voor gegevensdeling. Handmatig invoeren blijft mogelijk.'},
sv:{title:'Från din klocka\ntill din sömndagbok.',body:'Importera sömndata från Apple Watch eller en kompatibel smartklocka och fyll i din sömnregistrering automatiskt, med mindre manuell inmatning varje morgon.',note:'Tillgängliga integrationer beror på operativsystem, enhet och datadelningsinställningar. Du kan också registrera manuellt.'},
pl:{title:'Z zegarka\ndo dziennika snu.',body:'Importuj dane snu z Apple Watch lub zgodnego smartwatcha i automatycznie uzupełniaj zapis snu, ograniczając ręczne wpisywanie każdego ranka.',note:'Dostępne integracje zależą od systemu, urządzenia i ustawień udostępniania danych. Możesz też wpisywać dane ręcznie.'},
ru:{title:'С часов\nв дневник сна.',body:'Импортируйте данные сна с Apple Watch или совместимых смарт-часов и автоматически заполняйте запись сна, сокращая ручной ввод по утрам.',note:'Доступные интеграции зависят от ОС, устройства и настроек обмена данными. Можно также вводить записи вручную.'},
ar:{title:'من ساعتك\nإلى يوميات نومك.',body:'استورد بيانات النوم المسجلة عبر Apple Watch أو ساعة ذكية متوافقة لملء سجل نومك تلقائيًا وتقليل الإدخال اليدوي كل صباح.',note:'تعتمد خيارات الربط على نظام التشغيل والجهاز وإعدادات مشاركة البيانات. ويمكنك أيضًا إدخال السجلات يدويًا.'},
hi:{title:'आपकी घड़ी से\nआपकी नींद की डायरी तक।',body:'Apple Watch या संगत स्मार्टवॉच में दर्ज नींद का डेटा आयात करें और अपनी नींद का रिकॉर्ड अपने आप भरें। हर सुबह हाथ से जानकारी भरने का काम कम करें।',note:'उपलब्ध कनेक्शन आपके OS, डिवाइस और डेटा साझा करने की सेटिंग पर निर्भर हैं। आप हाथ से भी रिकॉर्ड भर सकते हैं।'},
th:{title:'จากนาฬิกา\nสู่บันทึกการนอนของคุณ',body:'นำเข้าข้อมูลการนอนจาก Apple Watch หรือสมาร์ตวอตช์ที่รองรับ เพื่อกรอกบันทึกการนอนโดยอัตโนมัติ ลดการป้อนข้อมูลเองทุกเช้า',note:'การเชื่อมต่อที่ใช้ได้ขึ้นอยู่กับระบบปฏิบัติการ อุปกรณ์ และการตั้งค่าการแชร์ข้อมูล คุณยังบันทึกด้วยตนเองได้'},
vi:{title:'Từ đồng hồ\nđến nhật ký giấc ngủ.',body:'Nhập dữ liệu giấc ngủ từ Apple Watch hoặc đồng hồ thông minh tương thích để tự động điền bản ghi, giảm việc nhập thủ công mỗi sáng.',note:'Khả năng kết nối phụ thuộc vào hệ điều hành, thiết bị và cài đặt chia sẻ dữ liệu. Bạn cũng có thể nhập thủ công.'},
id:{title:'Dari jam tangan\nke jurnal tidur Anda.',body:'Impor data tidur dari Apple Watch atau smartwatch yang kompatibel untuk mengisi catatan tidur secara otomatis dan mengurangi input manual setiap pagi.',note:'Integrasi yang tersedia bergantung pada OS, perangkat, dan pengaturan berbagi data. Anda juga dapat mencatat secara manual.'},
tr:{title:'Saatinizden\nuyku günlüğünüze.',body:'Apple Watch veya uyumlu bir akıllı saatin kaydettiği uyku verilerini içe aktararak uyku kaydınızı otomatik doldurun ve her sabah elle veri girişini azaltın.',note:'Kullanılabilir bağlantılar işletim sistemine, cihaza ve veri paylaşımı ayarlarına bağlıdır. Kayıtları elle de girebilirsiniz.'}
};
