import type {Locale} from './locales';
// Caption, timer alt, gallery heading, history description, stats description, detail description.
export const screenCopy:Record<Locale,[string,string,string,string,string,string]>={
ja:['英語版の実画面。表示・価格は撮影時点のものです。','最後の食事からの経過時間、ゴール、食事記録ボタンを表示したタイマー画面','記録を、いろいろな角度から。','日付・経過時間・ゴール到達状況を履歴で確認。','達成回数・最長時間・平均時間を、グラフと一緒に。','グラフの記録から、開始・終了時刻と経過時間を確認。'],
en:['Actual English-language screens. Interface and prices shown are from the time of capture.','Timer showing elapsed time since the last meal, a goal and the meal log button','Your records, from every angle.','Review dates, elapsed times and goal status in your history.','See completed goals, longest and average times alongside a chart.','Open a chart entry to see start and end times and duration.'],
'zh-CN':['英语版实际界面。显示内容及价格以截图时为准。','显示距上次进餐的时间、目标和进餐记录按钮的计时器界面','从不同角度，回顾记录。','在历史记录中查看日期、时长及目标达成情况。','通过图表查看达成次数、最长时间和平均时间。','打开图表中的记录，查看开始、结束时间及时长。'],
'zh-TW':['英語版實際畫面。顯示內容及價格以截圖時為準。','顯示距上次進餐的時間、目標和進餐記錄按鈕的計時器畫面','從不同角度，回顧記錄。','在歷史記錄中查看日期、時長及目標達成情況。','透過圖表查看達成次數、最長時間和平均時間。','開啟圖表中的記錄，查看開始、結束時間及時長。'],
ko:['영어판 실제 화면입니다. 표시 내용과 가격은 촬영 당시 기준입니다.','마지막 식사 후 경과 시간, 목표, 식사 기록 버튼이 있는 타이머 화면','다양한 관점에서 보는 기록.','기록에서 날짜, 경과 시간, 목표 달성 여부를 확인하세요.','달성 횟수, 최장 시간, 평균 시간을 그래프와 함께 확인하세요.','그래프의 기록을 열어 시작·종료 시각과 경과 시간을 확인하세요.'],
de:['Originalansichten auf Englisch. Oberfläche und Preise entsprechen dem Aufnahmezeitpunkt.','Timer mit Zeit seit der letzten Mahlzeit, Ziel und Taste zum Erfassen einer Mahlzeit','Deine Einträge im Überblick.','Prüfe Datum, Dauer und Zielstatus im Verlauf.','Sieh erreichte Ziele, längste und durchschnittliche Dauer mit Diagramm.','Öffne einen Diagrammeintrag für Start, Ende und Dauer.'],
fr:['Écrans réels en anglais. Interface et prix au moment de la capture.','Minuteur avec temps depuis le dernier repas, objectif et bouton de saisie du repas','Vos données sous plusieurs angles.','Consultez les dates, durées et objectifs atteints dans votre historique.','Retrouvez les objectifs atteints, la durée maximale et la moyenne avec un graphique.','Ouvrez une entrée du graphique pour consulter le début, la fin et la durée.'],
es:['Pantallas reales en inglés. Interfaz y precios del momento de la captura.','Temporizador con tiempo desde la última comida, objetivo y botón para registrar una comida','Tus registros, desde varios ángulos.','Consulta fechas, duración y estado del objetivo en tu historial.','Ve los objetivos completados, el tiempo máximo y el promedio junto al gráfico.','Abre un registro del gráfico para ver el inicio, el final y la duración.'],
it:['Schermate reali in inglese. Interfaccia e prezzi risalgono al momento della cattura.','Timer con tempo dall’ultimo pasto, obiettivo e pulsante per registrare un pasto','I tuoi dati, da più prospettive.','Consulta date, durate e stato degli obiettivi nella cronologia.','Visualizza obiettivi raggiunti, durata massima e media con il grafico.','Apri una voce del grafico per vedere inizio, fine e durata.'],
'pt-BR':['Telas reais em inglês. Interface e preços da época da captura.','Temporizador com tempo desde a última refeição, meta e botão para registrar uma refeição','Seus registros, por vários ângulos.','Consulte datas, duração e status das metas no histórico.','Veja metas concluídas, maior duração e média junto ao gráfico.','Abra um registro do gráfico para ver início, fim e duração.'],
nl:['Echte schermen in het Engels. Interface en prijzen ten tijde van de opname.','Timer met tijd sinds de laatste maaltijd, doel en knop om een maaltijd vast te leggen','Je gegevens vanuit meerdere hoeken.','Bekijk datums, tijden en doelstatus in je geschiedenis.','Zie behaalde doelen, langste en gemiddelde tijd naast een grafiek.','Open een grafiekitem voor begin, einde en duur.'],
sv:['Verkliga skärmar på engelska. Gränssnitt och priser vid skärmbildstillfället.','Timer med tid sedan senaste måltiden, mål och knapp för måltidsregistrering','Dina poster ur flera perspektiv.','Se datum, tider och målstatus i historiken.','Se uppnådda mål, längsta tid och genomsnitt tillsammans med diagrammet.','Öppna en diagrampost för att se start, slut och varaktighet.'],
pl:['Rzeczywiste ekrany w języku angielskim. Wygląd i ceny z chwili wykonania zrzutu.','Licznik czasu od ostatniego posiłku z celem i przyciskiem zapisu posiłku','Twoje wpisy z różnych perspektyw.','Sprawdzaj daty, czas i status celu w historii.','Zobacz osiągnięte cele, najdłuższy i średni czas obok wykresu.','Otwórz wpis na wykresie, aby zobaczyć początek, koniec i czas trwania.'],
ru:['Реальные экраны на английском. Интерфейс и цены на момент снимка.','Таймер с временем после последнего приёма пищи, целью и кнопкой записи еды','Ваши записи с разных сторон.','Проверяйте даты, длительность и достижение целей в истории.','Смотрите число достигнутых целей, наибольшее и среднее время вместе с графиком.','Откройте запись на графике, чтобы увидеть начало, конец и длительность.'],
ar:['شاشات فعلية باللغة الإنجليزية. الواجهة والأسعار وقت التقاط الصور.','شاشة المؤقّت تعرض الوقت منذ آخر وجبة والهدف وزر تسجيل الوجبة','سجلاتك من زوايا مختلفة.','راجع التواريخ والمدة وحالة بلوغ الهدف في السجل.','شاهد الأهداف المكتملة وأطول مدة والمتوسط مع الرسم البياني.','افتح سجلًا من الرسم لعرض وقت البداية والنهاية والمدة.'],
hi:['अंग्रेज़ी में वास्तविक स्क्रीन। इंटरफ़ेस और कीमतें स्क्रीनशॉट लेते समय की हैं।','पिछले भोजन से बीता समय, लक्ष्य और भोजन दर्ज करने का बटन दिखाती टाइमर स्क्रीन','अपने रिकॉर्ड, कई नज़रियों से।','इतिहास में तारीख, अवधि और लक्ष्य की स्थिति देखें।','पूरे हुए लक्ष्य, सबसे लंबी अवधि और औसत को ग्राफ़ के साथ देखें।','शुरुआत, अंत और अवधि देखने के लिए ग्राफ़ का कोई रिकॉर्ड खोलें।'],
th:['หน้าจอจริงภาษาอังกฤษ อินเทอร์เฟซและราคาแสดงตามที่บันทึกไว้','หน้าจอตัวจับเวลาแสดงเวลาที่ผ่านไปตั้งแต่มื้อล่าสุด เป้าหมาย และปุ่มบันทึกมื้ออาหาร','บันทึกของคุณ จากหลายมุมมอง','ดูวันที่ เวลาที่ผ่านไป และสถานะเป้าหมายในประวัติ','ดูเป้าหมายที่สำเร็จ เวลาที่นานที่สุด และเวลาเฉลี่ยพร้อมกราฟ','เปิดรายการในกราฟเพื่อดูเวลาเริ่มต้น สิ้นสุด และระยะเวลา'],
vi:['Giao diện thực tế bằng tiếng Anh. Giao diện và giá hiển thị tại thời điểm chụp.','Màn hình bộ đếm hiển thị thời gian từ bữa ăn gần nhất, mục tiêu và nút ghi bữa ăn','Dữ liệu của bạn, từ mọi góc nhìn.','Xem ngày, thời gian và trạng thái mục tiêu trong lịch sử.','Xem mục tiêu đạt được, thời gian dài nhất và trung bình cùng biểu đồ.','Mở mục trong biểu đồ để xem thời gian bắt đầu, kết thúc và thời lượng.'],
id:['Tampilan asli dalam bahasa Inggris. Antarmuka dan harga sesuai saat pengambilan gambar.','Layar timer menampilkan waktu sejak makan terakhir, target, dan tombol catat makan','Catatan Anda, dari berbagai sudut.','Tinjau tanggal, durasi, dan status target di riwayat.','Lihat target tercapai, waktu terlama, dan rata-rata bersama grafik.','Buka entri grafik untuk melihat waktu mulai, selesai, dan durasi.'],
tr:['İngilizce gerçek ekranlar. Arayüz ve fiyatlar çekim anındaki şekliyle gösterilmektedir.','Son öğünden bu yana geçen süreyi, hedefi ve öğün kaydetme düğmesini gösteren zamanlayıcı ekranı','Kayıtların, her açıdan.','Geçmişte tarihleri, süreleri ve hedef durumunu incele.','Tamamlanan hedefleri, en uzun ve ortalama süreleri grafikle birlikte gör.','Başlangıç, bitiş saatlerini ve süreyi görmek için grafik kaydını aç.']
};

